apiVersion: v1
kind: Secret
metadata:
  name: notifications-secret
  namespace: tds-group-3
type: Opaque
stringData:
  DB_HOST: "${NOTIFICATIONS_DB_HOST}"
  DB_PORT: "${NOTIFICATIONS_DB_PORT}"
  DB_NAME: "${NOTIFICATIONS_DB_NAME}"
  DB_USER: "${NOTIFICATIONS_DB_USER}"
  DB_PASSWORD: "${NOTIFICATIONS_DB_PASSWORD}"
  INTERNAL_SECRET: "${INTERNAL_SECRET}"
  LOKI_URL: "${LOKI_URL}"
  LOKI_USER: "${LOKI_USER}"
  LOKI_TOKEN: "${LOKI_TOKEN}"
