apiVersion: v1
kind: Service
metadata:
  name: notifications
  namespace: tds-group-3
  labels:
    app: notifications
spec:
  type: ClusterIP
  selector:
    app: notifications
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
